# Autogenerated by Astropy-affiliated package nustar_gen's setup.py on 2020-01-09 23:17:35 UTC
import datetime

version = "0.2"
githash = "265ded296851702c26ae7d90a3f770161ed8e10f"


major = 0
minor = 2
bugfix = 0

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2020, 1, 9, 23, 17, 35)
debug = False

astropy_helpers_version = "4.0.dev1188"
